# Generated by Django 4.1.1 on 2022-09-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("f1app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="races",
            old_name="circuit_id_2",
            new_name="race_circuit_id",
        ),
        migrations.RenameField(
            model_name="result",
            old_name="constructor_id",
            new_name="result_constructor_id",
        ),
        migrations.RenameField(
            model_name="result",
            old_name="driver_id",
            new_name="result_driver_id",
        ),
        migrations.RenameField(
            model_name="result",
            old_name="race_id",
            new_name="result_race_id",
        ),
        migrations.RemoveField(
            model_name="constructor",
            name="constructor_race_wins",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="championships",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="race_wins",
        ),
    ]
