# Generated by Django 4.1.1 on 2022-10-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("f1app", "0002_rename_circuit_id_2_races_race_circuit_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="races",
            old_name="race_circuit_id",
            new_name="circuit_id",
        ),
    ]
