# Generated by Django 4.1.1 on 2022-10-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("f1app", "0003_rename_race_circuit_id_races_circuit_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="races",
            old_name="circuit_id",
            new_name="circuit",
        ),
    ]
