# Generated by Django 4.1.1 on 2022-10-19 18:59

from django.db import migrations, models
import django_matplotlib.fields


class Migration(migrations.Migration):

    dependencies = [
        ("f1app", "0008_alter_result_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("figure", django_matplotlib.fields.MatplotlibFigureField()),
            ],
        ),
    ]
